#!/bin/bash

# don't write .DS_Store files on our Windows shares

defaults write com.apple.desktopservices DSDontWriteNetworkStores true


# create the `auto_mnt` automount map in which we will declare automounts for /mnt/auto.
# NOTE: only declare maps on **empty** directories!

grep -q auto_mnt /etc/auto_master || echo "/mnt/auto auto_mnt" | sudo tee -a /etc/auto_master >/dev/null


# set luapower as the only directory in the `auto` map.

echo "luapower smb://$USER:abcd12@10.0.0.5/x/luapower" | sudo tee /etc/auto_mnt >/dev/null


# restart the automounter

sudo automount -vc


# create a symlink to luapower in $HOME as needed by the CI scripts.

ln -sf /mnt/auto/luapower $HOME/


# test the mount

ls $HOME/luapower | wc -l
